M48
; DRILL file {KiCad (6.0.9)} date Mon Feb 20 20:30:59 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-20T20:30:59+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X151.45Y-117.935
T2
X123.49Y-121.08
X159.34Y-57.7
T3
X138.28Y-109.0
X148.46Y-71.75
X150.67Y-107.21
T0
M30
